### PR TITLE
Add import task to the rakefile

### PR DESCRIPTION
**Pull request by photomattmills**

### CODE REVIEW

**Comment by photomattmills** [comment]
Sorry about the whitespace changes, editor made me do it.

**Comment by sarahmei** [comment]
Here is where we discover that I'm a maintainer n00b. :dancer: 

Because I edited the README at the same time as you (to add a code of conduct), I can't merge this PR automatically. :( There's also something weird with the git setup my laptop that it isn't preserving your commit - when I do the merge, your commit disappears and everything is my fault, er, my work. :D

Terribly sorry but would you mind grabbing the new CoC changes, reapplying your changes, and then opening a new PR?

**Comment by photomattmills** [comment]
Rebased from master, should be good to go :smile:

**Comment by ben-biddington** [comment]
@mattmills, next try eliminating rails entirely. Maybe sqlite could be an option, too, @sarahmei?

**Comment by sarahmei** [comment]
@ben-biddington pull requests gladly accepted! :D 

I do think sqlite could be a good option, since embloggen is really only designed to run locally. It's postgres now just because that's my standard rails setup.

**Comment by ben-biddington** [comment]
Okay, I will take a look

**Pull request merged**
